# Generated by Django 5.1.5 on 2025-01-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=200)),
                ('case_description', models.CharField(max_length=300)),
                ('user_id', models.CharField(max_length=50)),
                ('serial_no', models.CharField(max_length=50)),
                ('court_no', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
