# Generated by Django 5.1.5 on 2025-01-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casedetails',
            old_name='serial_no',
            new_name='item_no',
        ),
    ]
