# Generated by Django 5.1.5 on 2025-01-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_rename_serial_no_casedetails_item_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseDetails',
        ),
    ]
