# Generated by Django 5.1.5 on 2025-01-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseDetails',
        ),
    ]
