# Generated by Django 5.1.5 on 2025-01-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal', '0005_delete_casedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('judge', models.CharField(max_length=50)),
                ('court_no', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
    ]
