# Generated by Django 5.1.5 on 2025-01-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0006_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casedetails',
            options={'verbose_name_plural': 'Case Details'},
        ),
    ]
