# Generated by Django 5.1.5 on 2025-01-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0007_alter_casedetails_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseDetails',
        ),
    ]
