# Generated by Django 5.1.5 on 2025-01-29 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='case_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal.caseentry'),
        ),
    ]
