# Generated by Django 5.1.5 on 2025-01-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0010_caseentry_alter_casedetails_case_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='case_no',
            field=models.CharField(max_length=50),
        ),
    ]
