# Generated by Django 5.1.5 on 2025-01-29 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0011_alter_casedetails_case_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='case_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal.caseentry'),
        ),
    ]
