# Generated by Django 5.1.5 on 2025-01-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0012_alter_casedetails_case_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseentry',
            options={'verbose_name_plural': 'Case Entries '},
        ),
    ]
