# Generated by Django 5.1.5 on 2025-01-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal', '0014_delete_casedetails_delete_caseentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Case Entries ',
            },
        ),
    ]
