# Generated by Django 5.1.5 on 2025-01-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0015_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('judge', models.CharField(max_length=50)),
                ('court_no', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('case_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal.caseentry')),
            ],
            options={
                'verbose_name_plural': 'Case Details',
            },
        ),
    ]
