# Generated by Django 5.1.5 on 2025-01-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0016_casedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='description',
            field=models.TextField(default='not yet posted'),
        ),
    ]
